/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef counter_TYPES_H
#define counter_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace counterService {

//typedef int32_t int;

class Account;

class ServerFigure;

typedef struct _Account__isset {
  _Account__isset() : id(false), visitor(false) {}
  bool id :1;
  bool visitor :1;
} _Account__isset;

class Account {
 public:

  static const char* ascii_fingerprint; // = "EEBC915CE44901401D881E6091423036";
  static const uint8_t binary_fingerprint[16]; // = {0xEE,0xBC,0x91,0x5C,0xE4,0x49,0x01,0x40,0x1D,0x88,0x1E,0x60,0x91,0x42,0x30,0x36};

  Account(const Account&);
  Account& operator=(const Account&);
  Account() : id(), visitor(0) {
  }

  virtual ~Account() throw();
  std::string id;
  int visitor;

  _Account__isset __isset;

  void __set_id(const std::string& val);

  void __set_visitor(const int val);

  bool operator == (const Account & rhs) const
  {
    if (!(id == rhs.id))
      return false;
    if (!(visitor == rhs.visitor))
      return false;
    return true;
  }
  bool operator != (const Account &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Account & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Account& obj);
};

void swap(Account &a, Account &b);

typedef struct _ServerFigure__isset {
  _ServerFigure__isset() : listAccount(false), totalVisitor(false) {}
  bool listAccount :1;
  bool totalVisitor :1;
} _ServerFigure__isset;

class ServerFigure {
 public:

  static const char* ascii_fingerprint; // = "9588C61CD15F295DFB8708BE1D96FF9D";
  static const uint8_t binary_fingerprint[16]; // = {0x95,0x88,0xC6,0x1C,0xD1,0x5F,0x29,0x5D,0xFB,0x87,0x08,0xBE,0x1D,0x96,0xFF,0x9D};

  ServerFigure(const ServerFigure&);
  ServerFigure& operator=(const ServerFigure&);
  ServerFigure() : totalVisitor(0) {
  }

  virtual ~ServerFigure() throw();
  std::vector<Account>  listAccount;
  int totalVisitor;

  _ServerFigure__isset __isset;

  void __set_listAccount(const std::vector<Account> & val);

  void __set_totalVisitor(const int val);

  bool operator == (const ServerFigure & rhs) const
  {
    if (!(listAccount == rhs.listAccount))
      return false;
    if (!(totalVisitor == rhs.totalVisitor))
      return false;
    return true;
  }
  bool operator != (const ServerFigure &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ServerFigure & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const ServerFigure& obj);
};

void swap(ServerFigure &a, ServerFigure &b);

} // namespace

#endif
