// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Counter.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::counterService;

class CounterHandler : virtual public CounterIf {
 public:
  CounterHandler() {
    // Your initialization goes here
  }

  bool put(const std::string& id, const int putType) {
    // Your implementation goes here
    printf("put\n");
  }

  int getTotal() {
    // Your implementation goes here
    printf("getTotal\n");
  }

  int get(const std::string& id) {
    // Your implementation goes here
    printf("get\n");
  }

  void inc(const std::string& id) {
    // Your implementation goes here
    printf("inc\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<CounterHandler> handler(new CounterHandler());
  shared_ptr<TProcessor> processor(new CounterProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

